name: Build For Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v4.1.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        go-version: 1.21

    - name: Add Dependencies
      run: apt install libseccomp-dev
        
    - name: Build Project
      run: make
      
    - name: Upload files to a GitHub release
      # You may pin to the exact commit or the version.
      # uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df
      uses: svenstaro/upload-release-action@2.7.0
      with:
        # GitHub token.
        repo_token: ${{ secrets.GH_TOKEN }}
        # Local file to upload.
        file: build/*
        # Name of the asset. When not provided will use the file name. Unused if file_glob is set to "true".
        asset_name: true
        # Overwrite the release in case it already exists.
        overwrite: true
        # Promote a prerelease to release. Defaults to "false".
        promote: true
        # If true the file can be a glob pattern, asset_name is ignored if this is true.
        file_glob: true
